# Generated by Django 3.0.7 on 2020-06-25 06:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200625_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userobject',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userobject',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='username',
        ),
    ]
